version: '3'

services:
  backend:
    image: todo/backend-image
    container_name: backend-container
    networks:
      - front-back-bridge
    ports:
      - "8000:8000"

  frontend:
    image: todo/frontend-image
    container_name: frontend-container
    networks:
      - front-back-bridge
    ports:
      - "5173:5173"

networks:
  front-back-bridge:
    driver: bridge
